### ISSUE TITLE
Create pipeline using hydra-genetics based pipeline

### ISSUE THREAD

**Issue by ljmesi** [genomic-medicine-sweden/pgx#1]
The existing pipeline should be converted to one base on hydra-genetics
## Tasks
- [x] create pipeline using hydra-genetics (suggested name pgx, but feel free to come up with a new name) 
- [x] create a repository at [genomic medicin sweden ](https://github.com/genomic-medicine-sweden)

  -  update Twist_Solid/.github/CODEOWNERS to  automatically include people that should review pull-request (feel free to add Smeds)

- [x] push repo github

## input 
- bed
- bam

## output
report

### Repo
https://github.com/JoelAAs/pgx_module
### Dag
![Image](https://user-images.githubusercontent.com/5391226/166433333-b0a70e26-6343-4575-a345-0df2891374f4.png)

## Other
Please follow [hydra-genetics guidelines](https://docs.google.com/document/d/1l2v1ItZBTDaI72vQPZcaQzxwVUao78XzIJvGASAAD9E/edit?usp=sharing)
